databases:
  - name: eventhub-db
    databaseName: eventhub
    user: eventhub_user
    plan: free

services:
  - type: web
    name: eventhub
    runtime: python
    buildCommand: |
      cd eventapp
      pip install -r requirements.txt
      flask db init || true
      flask db migrate -m "Initial migration" || true
      flask db upgrade
      cd ..
      python seed.py
    startCommand: python index.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: eventhub-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: eventapp
      - key: CLOUDINARY_CLOUD_NAME
        sync: false  # Render sẽ lấy từ Environment Variables đã set sẵn
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
    plan: free
    healthCheckPath: /
    autoDeploy: false