databases:
  - name: eventhub-db
    databaseName: eventhub
    user: eventhub_user
    plan: free

services:
  - type: web
    name: eventhub
    runtime: python3
    buildCommand: |
      pip install -r requirements.txt
      flask db init || true
      flask db migrate -m "Initial migration" || true
      flask db upgrade
      python seed.py
    startCommand: python index.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: eventhub-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: index.py
      - key: CLOUDINARY_CLOUD_NAME
        value: os.getenv('CLOUDINARY_CLOUD_NAME', 'your_cloudinary_cloud_name')
      - key: CLOUDINARY_API_KEY
        value: os.getenv('CLOUDINARY_API_KEY', 'your_cloudinary_api_key')
      - key: CLOUDINARY_API_SECRET
        value: os.getenv('CLOUDINARY_API_SECRET', 'your_cloudinary_api_secret')
    plan: free
    healthCheckPath: /
    autoDeploy: false