"""Initial migration

Revision ID: 33bef49d5780
Revises: 
Create Date: 2025-07-19 16:56:26.475544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33bef49d5780'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('ticket_type_id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('qr_code_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.Column('is_checked_in', sa.Boolean(), nullable=False),
    sa.Column('check_in_date', sa.DateTime(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['ticket_type_id'], ['ticket_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.create_index('ix_ticket_qr_code', ['qr_code_url'], unique=False)
        batch_op.create_index('ix_ticket_type', ['ticket_type_id'], unique=False)
        batch_op.create_index('ix_ticket_user_event', ['user_id', 'event_id'], unique=False)

    op.create_table('user_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_email_sent', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'notification_id', name='unique_user_notification')
    )
    with op.batch_alter_table('user_notifications', schema=None) as batch_op:
        batch_op.create_index('ix_user_notification_user_notif', ['user_id', 'notification_id'], unique=False)
        batch_op.create_index('ix_user_notification_user_read', ['user_id', 'is_read'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_user_notification_user_read')
        batch_op.drop_index('ix_user_notification_user_notif')

    op.drop_table('user_notifications')
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_index('ix_ticket_user_event')
        batch_op.drop_index('ix_ticket_type')
        batch_op.drop_index('ix_ticket_qr_code')

    op.drop_table('tickets')
    # ### end Alembic commands ###
