"""empty message

Revision ID: 3fa92adb3b96
Revises: c8b57c1b3a74
Create Date: 2025-08-26 15:08:38.152461

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3fa92adb3b96'
down_revision = 'c8b57c1b3a74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_notifications', schema=None) as batch_op:
        batch_op.drop_column('is_email_sent')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_email_sent', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
