"""empty message

Revision ID: 783c389accbc
Revises: 2cbb6e2a9370
Create Date: 2025-08-25 15:16:52.041973

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '783c389accbc'
down_revision = '2cbb6e2a9370'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('payment_method',
               existing_type=mysql.ENUM('momo', 'vnpay'),
               type_=sa.Enum('vnpay', 'momo', name='paymentmethod'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('payment_method',
               existing_type=sa.Enum('vnpay', 'momo', name='paymentmethod'),
               type_=mysql.ENUM('momo', 'vnpay'),
               existing_nullable=False)

    # ### end Alembic commands ###
