name: CI - Run Tests

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r eventapp/requirements.txt

      - name: Set environment variables
        run: |
          echo "DATABASE_URL=sqlite:///test.db" >> $GITHUB_ENV
          echo "FLASK_APP=eventapp" >> $GITHUB_ENV
          echo "FLASK_ENV=testing" >> $GITHUB_ENV
          echo "SECRET_KEY=test_secret" >> $GITHUB_ENV

      - name: Run tests
        run: |
          pytest eventapp/tests --maxfail=1 --disable-warnings -q